name: Configurar Variaveis na Vercel

on:
  workflow_dispatch:

jobs:
  setup-env:
    runs-on: ubuntu-latest
    steps:
      - name: Add ZAPI vars
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          curl -sf -X POST "https://api.vercel.com/v10/projects/devocionalai/env?teamId=joaolsouza1407-pngs-projects" -H "Authorization: Bearer $VERCEL_TOKEN" -H "Content-Type: application/json" -d '{"key":"ZAPI_INSTANCE_ID","value":"3F29265543BCD1B34FAA12DF64D7129F","type":"encrypted","target":["production"]}'
          curl -sf -X POST "https://api.vercel.com/v10/projects/devocionalai/env?teamId=joaolsouza1407-pngs-projects" -H "Authorization: Bearer $VERCEL_TOKEN" -H "Content-Type: application/json" -d '{"key":"ZAPI_TOKEN","value":"9AD8213337ABEF9C2F573EEC","type":"encrypted","target":["production"]}'
          curl -sf -X POST "https://api.vercel.com/v10/projects/devocionalai/env?teamId=joaolsouza1407-pngs-projects" -H "Authorization: Bearer $VERCEL_TOKEN" -H "Content-Type: application/json" -d '{"key":"ZAPI_CLIENT_TOKEN","value":"Fca4db9a5d5be4e60963d9c903f75aae6S","type":"encrypted","target":["production"]}'
          echo Done
